# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipctl < Formula
  desc "A tool to perform various network troubleshooting"
  homepage "https://github.com/kartverket/skipctl"
  version "1.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kartverket/skipctl/releases/download/v1.9.0/skipctl_Darwin_x86_64.tar.gz"
      sha256 "fcee327c845c6ebe0523b093f5c5f18d86799b7ff4b495767d8aae6992211666"

      def install
        bin.install "skipctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kartverket/skipctl/releases/download/v1.9.0/skipctl_Darwin_arm64.tar.gz"
      sha256 "8860fa06ecdb1d2836786a55d2e36c4725a2b6a5678a0b82a11a7688577b7183"

      def install
        bin.install "skipctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kartverket/skipctl/releases/download/v1.9.0/skipctl_Linux_x86_64.tar.gz"
      sha256 "dae767a0587fb98bf6b02baafa53f4c945c19531836093240015c266515996cc"
      def install
        bin.install "skipctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kartverket/skipctl/releases/download/v1.9.0/skipctl_Linux_arm64.tar.gz"
      sha256 "4df088b13a36bad398451ca5ce2c2554a444deccba96bb10d4bd79b75d4f7111"
      def install
        bin.install "skipctl"
      end
    end
  end

  def caveats
    <<~EOS
      Contact SKIP with feature requests or questions (#gen-skip).
    EOS
  end

  test do
    system "#{bin}/skipctl --version"
  end
end
