# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipctl < Formula
  desc "A tool to perform various network troubleshooting"
  homepage "https://github.com/kartverket/skipctl"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/kartverket/skipctl/releases/download/v1.0.0/skipctl_Darwin_x86_64.tar.gz"
      sha256 "f58c11aacee37bbdb8c7f587296287d641b96ffa7e0bdf872d6d627902f81237"

      def install
        bin.install "skipctl"
      end
    end
    on_arm do
      url "https://github.com/kartverket/skipctl/releases/download/v1.0.0/skipctl_Darwin_arm64.tar.gz"
      sha256 "2ef52f0444d5e5b3dbe21f6e2200e3054f6fddf2c88c58dcb0900eea4b2c993b"

      def install
        bin.install "skipctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kartverket/skipctl/releases/download/v1.0.0/skipctl_Linux_x86_64.tar.gz"
        sha256 "da6d2d4c7b500aebe0d671c33f9132bed5139a4788810693930fa7b1b085ed3c"

        def install
          bin.install "skipctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kartverket/skipctl/releases/download/v1.0.0/skipctl_Linux_arm64.tar.gz"
        sha256 "179a7494b268e340cbe38b5d898c8f92aab1a797d70f909a6abbe59807881a73"

        def install
          bin.install "skipctl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Contact SKIP with feature requests or questions (#gen-skip).
    EOS
  end

  test do
    system "#{bin}/skipctl --version"
  end
end
